version : "3"
services:
    mysql:
        build: "./mysql"
        volumes:
            - ./mysql/sql:/home/root
            - ./mysql/db:/docker-entrypoint-initdb.d
        image:
            original_mysql
        environment:
            - MYSQL_ROOT_PASSWORD=mysql
